name: Format

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pages: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  format_and_open_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run formatter and open PR
        run: |
            current_dir="$(basename "$PWD")"

            git config user.email "github-actions@github.com"
            git config user.name "github-actions"

            if [ -d "$current_dir" ]; then
                cd "$current_dir"
                cargo fmt
                cd ../

                if [ -n "$(git status --porcelain)" ]; then
                  git push --delete origin formatter
                  git checkout -b formatter
                  git add .
                  git commit -m "Format code"
                  git push origin formatter

                  gh pr create --base main --head formatter --title "Format code" --body "This pull request contains formatted code."
                  echo "Formatted repo and opened pr"
                else
                  echo "Nothing to format"
                fi
            else
                echo "No project folder was found: $current_dir"
            fi